# FGD Selasa Pagi 

## 08-Maret-2022

### Latihan-4 (Operasi matriks)

In [ ]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:
*   2*A
*   2+A
*   A+B
*   A-B
*   determinan A
*   invers dari B, simpan jadi matriks D
*   transpose D
*   nilai eigen dan vektor eigen dari A dan B







In [10]:
import numpy as np

A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])
D = np.linalg.inv(B)

eigen_A,eigen_vector_A=(np.linalg.eig(A))
eigen_B,eigen_vector_B=(np.linalg.eig(B))

print("Matriks A*2")
print(2*A)
print("\nMatriks A+2")
print(2+A)
print("\nMatriks A+B")
print(A+B)
print("\nMatriks A-B")
print(A-B)
print("\nDeterminan Matriks A")
print(np.linalg.det(A))
print("\nInvers Matriks B = D")
print(np.linalg.inv(B))
print("\nTranspose D")
print(np.transpose(D))

print("\nNilai eigen dan vekktor Eigen A dan B")
print("\nNilai eigen A")
print(eigen_A)
print("\nNilai eigen vektor A")
print(eigen_vector_A)
print("\nNilai eigen B")
print(eigen_B)
print("\nNilai eigen vektor B")
print(eigen_vector_B)

Matriks A*2
[[ 2  4]
 [14 16]]

Matriks A+2
[[ 3  4]
 [ 9 10]]

Matriks A+B
[[ 4  7]
 [ 8 14]]

Matriks A-B
[[-2 -3]
 [ 6  2]]

Determinan Matriks A
-6.0

Invers Matriks B = D
[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]

Transpose D
[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]

Nilai eigen dan vekktor Eigen A dan B

Nilai eigen A
[-0.62347538  9.62347538]

Nilai eigen vektor A
[[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]

Nilai eigen B
[1.8074176 7.1925824]

Nilai eigen vektor B
[[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)? 

In [35]:
print("Perkalian Entry B*D = ")
print(B*D)
print("")
print("Perkalian Matriks BD = ")
print(np.matmul(B,D))
      


Perkalian Entry B*D = 
[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]

Perkalian Matriks BD = 
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


output jawaban: 

perkalian entry = [[ 1.38461538, -1.92307692], [-0.07692308,  1.38461538]]

perkalian matriks = [[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]]
